const mockData = [
  {
    CP_ID: "1",
    HAZARD_NO: "1",
    SIDE: "C",
    LEVEL: "1",
    ORDER: "1",
    DETAIL: "LOPC From Feed Inlet Separator",
    INDICATOR: "RED",
  },
  {
    CP_ID: "2",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "1",
    ORDER: "1",
    DETAIL: "[Inlet Speparator] 3501",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "3",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "1",
    ORDER: "2",
    DETAIL: "[Feed Gas Inlet] Warm flare (49.5 barg)",
    INDICATOR: "YELLOW",
  },
  {
    CP_ID: "4",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "1",
    ORDER: "3",
    DETAIL: "[Feed Gas Inlet] Trip Closes XV-001",
    INDICATOR: "ORANGE",
  },
  {
    CP_ID: "5",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "2",
    ORDER: "1",
    DETAIL:
      "[DeC1 Trim Reboiler] 3503-PZHH Preventing Gas flow to hot oil System",
    INDICATOR: "RED",
  },
  {
    CP_ID: "6",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "2",
    ORDER: "2",
    DETAIL:
      "Two dissimilar check values preventing gas flow into hot oil supply line",
    INDICATOR: "RED",
  },
  {
    CP_ID: "7",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "2",
    ORDER: "3",
    DETAIL: "[DeC1 Trim Reboiler] and operator response",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "8",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "2",
    ORDER: "4",
    DETAIL:
      "[Hot Oil Return] 3503-LAL-017 (Standpipe Leak Detection) and Operator Response",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "9",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "3",
    ORDER: "1",
    DETAIL:
      "[Hot Oil Return] 3503-LAL-018 (Standpipe Leak Detection) and Operator Response",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "10",
    HAZARD_NO: "1",
    SIDE: "L",
    LEVEL: "3",
    ORDER: "2",
    DETAIL: "[Ethane Heater] 3511-PAH-011 (15 barg) and Operator Response",
    INDICATOR: "YELLOW",
  },
  {
    CP_ID: "11",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "1",
    ORDER: "1",
    DETAIL: "Refer to other MAE Bowties for mitigation factors",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "12",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "1",
    ORDER: "2",
    DETAIL:
      "[Ethane Product Heater] 3519-SV-003 (24 barg) to hot oil drain drum (for thermal expansion only)",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "13",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "2",
    ORDER: "1",
    DETAIL:
      "[Ethane Product Heater] 3519-PZHH-003 (20 barg) closes preventing gas flow to hot oil system (SIL1)",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "14",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "3",
    ORDER: "1",
    DETAIL:
      "Two dissimilar check values preventing gas flow into hot oil supply line",
    INDICATOR: "RED",
  },
  {
    CP_ID: "15",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "3",
    ORDER: "2",
    DETAIL:
      "[Hot Oil Return] 3503-LAL-004 (Standpipe Leak Detection) and Operator Response",
    INDICATOR: "RED",
  },
  {
    CP_ID: "16",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "3",
    ORDER: "3",
    DETAIL:
      "[Hot Oil Return] 3503-LAR-098 (Standpipe Leak Detection) and Operator Response",
    INDICATOR: "YELLOW",
  },
  {
    CP_ID: "17",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "3",
    ORDER: "4",
    DETAIL:
      "Manual fire detection and fire team applies foam to liquid pool fire",
    INDICATOR: "ORANGE",
  },
  {
    CP_ID: "18",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "4",
    ORDER: "1",
    DETAIL: "Personnel evacuation based on site ERP",
    INDICATOR: "GREEN",
  },
  {
    CP_ID: "18",
    HAZARD_NO: "1",
    SIDE: "R",
    LEVEL: "5",
    ORDER: "1",
    DETAIL: "Personnel evacuation based on site ERP",
    INDICATOR: "GREEN",
  },
];

export default mockData;
